export const PRIVACY_POLICY = `Privacy Policy`;

export const PRIVACY_POLICY_OF_SSDM_TITLE = `Privacy Policy of SSDM Limited mobile App`;
export const PRIVACY_POLICY_OF_SSDM = `SSDM Ltd has created the following Privacy Policy to let you know what information we collect when you visit our mobile App, why we collect it and how it is used. This Privacy Policy explains the data collection and use practices of SSDM mobile App; it does not apply to other online or offline SSDM sites, products, or services. The terms “you,” “your,” and “yours” refer to the customer/purchaser utilizing our Site. The terms “SSDM,” “SSDM” “we,” “us,” and “our” refer to SSDM. By using this website, you consent to the data practices prescribed in this statement. We may periodically post changes to this Privacy Policy on this page, and it is your responsibility to review this Privacy Policy frequently and we encourage you to visit this page often. When required by law, we will notify you of any changes to this Privacy Policy.`;

export const COLLECT_INFO_TITLE = `How we collect information about you`;
export const COLLECT_INFO_1 = `When you use SSDM Services, or use third-party services which use the SSDM application programming interface (“API”), we collect information sent to us through your computer, mobile phone, or other access device. This information may include your IP address, device information including, but not limited to, identifier, device name and type, operating system, location, mobile network information, and standard web log information, such as your browser type, traffic to and from our site, and the pages you accessed on our website. You must be at least 18 years old, or of the applicable age of majority, in order to use SSDM Services.`;
export const COLLECT_INFO_2 = `SSDM will not sell or rent any of your personal information to third parties and only shares your personal information with third parties as described in this policy. Before SSDM shares your information with any third party that is not acting as an agent to perform tasks on behalf of and under the instructions of SSDM, SSDM will enter into a written agreement requiring that the third party to provide at least the same level of privacy protection as required hereunder. In general, we will notify you of material changes to this policy by updating the last updated date at the top of this page, and we will provide you with explicit notice of material changes as required by law. We recommend that you visit this page frequently to check for changes.`;

export const CONTACT_US_TITLE = `How you can contact us about privacy questions`;
export const CONTACT_US = `If you have questions or concerns regarding this policy, or if you have a complaint, you should first contact us at support@ssdm.com.`;
